// User access actions
export const REQUEST_ACCESS_TOKEN = 'REQUEST_ACCESS_TOKEN'
export const REFRESH_SESSION = 'REFRESH_SESSION'
export const GLOBAL_SIGNOUT = 'GLOBAL_SIGNOUT'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD'

// Operation actions
export const FETCH_USER_PROPERTY = 'FETCH_USER_PROPERTY'
export const SEARCH_QUESTIONS = 'SEARCH_QUESTIONS'
export const FETCH_SURVEY_ANSWER = 'FETCH_SURVEY_ANSWER'
export const FETCH_PROPERTY_SUBURB = 'FETCH_PROPERTY_SUBURB'
export const SUBMIT_SURVEY_ANSWER = 'SUBMIT_SURVEY_ANSWER'
export const FETCH_PROPERTY_SUMMARY = 'FETCH_PROPERTY_SUMMARY'
export const FETCH_LOCATION_SUMMARY = 'FETCH_LOCATION_SUMMARY'
export const FETCH_PROXIMITY_ASSESSMENT = 'FETCH_PROXIMITY_ASSESSMENT'
export const FETCH_LAND_HOUSE_ASSESSMENT = 'FETCH_LAND_HOUSE_ASSESSMENT'
export const FETCH_REMAINED_QUESTIONS = 'FETCH_REMAINED_QUESTIONS'

// Suburb actions
export const UPSERT_SUBURB = 'UPSERT_SUBURB'
export const DELETE_SUBURB = 'DELETE_SUBURB'
export const FETCH_SUBURBS = 'FETCH_SUBURBS'
export const INIT_CURRENT_SUBURB = 'INIT_CURRENT_SUBURB'
export const FETCH_CURRENT_SUBURB = 'FETCH_CURRENT_SUBURB'
export const SAVE_SUBURB_SERVICE = 'SAVE_SUBURB_SERVICE'
export const DELETE_SUBURB_SERVICE = 'DELETE_SUBURB_SERVICE'
export const SAVE_SUBURB_DATA_PROVIDER = 'SAVE_SUBURB_DATA_PROVIDER'
export const DELETE_SUBURB_DATA_PROVIDER = 'DELETE_SUBURB_DATA_PROVIDER'

// Question actions
export const UPSERT_QUESTION = 'UPSERT_QUESTION'
export const DEACTIVATE_QUESTION = 'DEACTIVATE_QUESTION'
export const FETCH_QUESTIONS = 'FETCH_QUESTIONS'
export const INIT_CURRENT_QUESTION = 'INIT_CURRENT_QUESTION'
export const FETCH_CURRENT_QUESTION = 'FETCH_CURRENT_QUESTION'
export const UPDATE_CURRENT_QUESTION = 'UPDATE_CURRENT_QUESTION'
export const SAVE_QUESTION_RESPONSE = 'SAVE_QUESTION_RESPONSE'
export const DELETE_QUESTION_RESPONSE = 'DELETE_QUESTION_RESPONSE'

// Suburb proximity rule actions
export const ADD_PROXIMITY_RULE = 'ADD_PROXIMITY_RULE'
export const UPDATE_PROXIMITY_RULE = 'UPDATE_PROXIMITY_RULE'
export const UPDATE_CURRENT_PROXIMITY_RULE = 'UPDATE_CURRENT_PROXIMITY_RULE'
export const DELETE_PROXIMITY_RULE = 'DELETE_PROXIMITY_RULE'
export const FETCH_PROXIMITY_RULES = 'FETCH_PROXIMITY_RULES'
export const FETCH_CURRENT_PROXIMITY_RULE = 'FETCH_CURRENT_PROXIMITY_RULE'
export const INIT_CURRENT_PROXIMITY_RULE = 'INIT_CURRENT_PROXIMITY_RULE'
export const SAVE_MEASURE = 'SAVE_MEASURE'
export const DELETE_MEASURE = 'DELETE_MEASURE'

// Suburb Scoring Rule Actions
export const FETCH_SCORING_RULES = 'FETCH_SCORING_RULES'
export const ADD_SCORING_RULE = 'ADD_SCORING_RULE'
export const DELETE_SCORING_RULE = 'DELETE_SCORING_RULE'
export const INIT_TEMPLATE_SCORING_RULES = 'INIT_TEMPLATE_SCORING_RULES'
export const FETCH_CALCULATION_METHODS = 'FETCH_CALCULATION_METHODS'
export const SAVE_SCORING_RULE = 'SAVE_SCORING_RULE'
export const UPSERT_SCORING_RULE = 'UPSERT_SCORING_RULE'
export const FETCH_SUBURB_SCORING_RULES = 'FETCH_SUBURB_SCORING_RULES'

// Reference actions
export const FETCH_SERVICE_CLASSIFICATION = 'FETCH_SERVICE_CLASSIFICATION'
export const FETCH_QUESTION_CLASSIFICATION = 'FETCH_QUESTION_CLASSIFICATION'
export const FETCH_ANALYSIS_TYPES = 'FETCH_ANALYSIS_TYPES'
export const FETCH_REPORT_CONTENT_TYPES = 'FETCH_REPORT_CONTENT_TYPES'
export const FETCH_PROPERTY_TYPES = 'FETCH_PROPERTY_TYPES'

// Config actions
export const LOAD_GOOGLE_MAPS_API = 'LOAD_GOOGLE_MAPS_API'

// content fragment actions
export const FETCH_CONTENT_FRAGMENTS = 'FETCH_CONTENT_FRAGMENTS'
export const DELETE_CONTENT_FRAGMENT = 'DELETE_CONTENT_FRAGMENT'
export const SAVE_CONTENT_FRAGMENTS = 'SAVE_CONTENT_FRAGMENTS'
