// User mutations
export const SET_TOKENS = 'SET_TOKENS'
export const SET_USER_STATUS = 'SET_USER_STATUS'
export const SET_PROFILE = 'SET_PROFILE'
export const REMOVE_TOKENS = 'REMOVE_TOKENS'

// Operation mutations
export const SET_USER_PROPERTY = 'SET_USER_PROPERTY'
export const SET_SURVEY_ANSWER = 'SET_SURVEY_ANSWER'
export const SET_PROPERTY_SUBURB = 'SET_PROPERTY_SUBURB'
export const SET_PROPERTY_SURVEYS = 'SET_PROPERTY_SURVEYS'
export const SET_PROPERTY_QUESTIONS = 'SET_PROPERTY_QUESTIONS'
export const SET_OVERALL_ASSESSMENT = 'SET_OVERALL_ASSESSMENT'
export const SET_LAND_HOUSE_ASSESSMENT = 'SET_LAND_HOUSE_ASSESSMENT'
export const SET_LOCATION_ASSESSMENT = 'SET_LOCATION_ASSESSMENT'
export const SET_PROPERTY_CONTENT_FRAGMENTS = 'SET_PROPERTY_CONTENT_FRAGMENTS'
export const SET_SURVEY_QUESTIONS = 'SET_SURVEY_QUESTIONS'
export const SET_PROXIMITY_ASSESSMENT = 'SET_PROXIMITY_ASSESSMENT'
export const SET_COMPARATIVE_RANKING = 'SET_COMPARATIVE_RANKING'
export const SET_REMAINED_QUESTIONS = 'SET_REMAINED_QUESTIONS'

// Fetching mutations
export const SET_LOADING = 'SET_LOADING'

// Suburb mutations
export const SET_SUBURBS = 'SET_SUBURBS'
export const SET_CURRENT_SUBURB = 'SET_CURRENT_SUBURB'
export const SET_ORIGINAL_SUBURB = 'SET_ORIGINAL_SUBURB'

// Question mutations
export const SET_QUESTION_QUERY = 'SET_QUESTION_QUERY'
export const SET_QUESTIONS = 'SET_QUESTIONS'
export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION'
export const SET_ORIGINAL_QUESTION = 'SET_ORIGINAL_QUESTION'

// Suburb proximity rule mutations
export const SET_PROXIMITY_RULES = 'SET_PROXIMITY_RULES'
export const SET_CURRENT_PROXIMITY_RULE = 'SET_CURRENT_PROXIMITY_RULE'
export const SET_MEASURE = 'SET_MEASURE'
export const SET_HAS_PENDING_CHANGES = 'SET_HAS_PENDING_CHANGES'

// Scoring Rule mutations
export const SET_SCORING_RULES = 'SET_SCORING_RULES'
export const SET_CURRENT_SCORING_RULE = 'SET_CURRENT_SCORING_RULE'
export const ADD_SCORING_RULE_TO_STATE = 'ADD_SCORING_RULE_TO_STATE'
export const SET_CALCULATION_METHODS = 'SET_CALCULATION_METHODS'

// Reference mutations
export const SET_REFERENCE_STATE = 'SET_REFERENCE_STATE'
export const SET_SERVICE_CLASSIFICATION = 'SET_SERVICE_CLASSIFICATION'
export const SET_QUESTION_CLASSIFICATION = 'SET_QUESTION_CLASSIFICATION'
export const SET_REPORT_CONTENT_TYPES = 'SET_REPORT_CONTENT_TYPES'
export const SET_ANALYSIS_TYPES = 'SET_ANALYSIS_TYPES'
export const SET_PROPERTY_TYPES = 'SET_PROPERTY_TYPES'

// Config mutations
export const SET_CONFIG_STATE = 'SET_CONFIG_STATE'

// Content fragments
export const SET_CONTENT_FRAGMENTS = 'SET_CONTENT_FRAGMENTS'
export const SET_CONTENT_FRAGMENTS_ERROR = 'SET_CONTENT_FRAGMENTS_ERROR'
